-- Plan comptable général 2026
-- Source : règlement ANC n° 2014-03 (version au 1er janvier 2026), PDF officiel ANC.
-- 831 comptes, dont 509 marqués optionnels (italiques dans le PDF) et 60 rubriques
-- de niveau 2 (non sélectionnables pour qualification, mais utiles pour la hiérarchie).
--
-- Le champ "optionnel" reflète la distinction du règlement : les comptes imprimés en
-- caractères italiques dans le PDF sont d'utilisation facultative. L'admin peut
-- basculer ce flag pour adapter la sélection via l'interface admin.

CREATE TABLE plan_comptable (
    numero VARCHAR(10) PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL,
    classe SMALLINT NOT NULL CHECK (classe BETWEEN 1 AND 9),
    optionnel BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_plan_comptable_classe ON plan_comptable(classe);
CREATE INDEX idx_plan_comptable_libelle_lower ON plan_comptable(LOWER(libelle));

INSERT INTO plan_comptable (numero, libelle, classe, optionnel) VALUES
  ('10', 'Capital et réserves', 1, FALSE),
  ('101', 'Capital', 1, FALSE),
  ('1011', 'Capital souscrit - non appelé', 1, TRUE),
  ('1012', 'Capital souscrit - appelé, non versé', 1, TRUE),
  ('1013', 'Capital souscrit - appelé, versé', 1, TRUE),
  ('10131', 'Capital non amorti', 1, TRUE),
  ('10132', 'Capital amorti', 1, TRUE),
  ('1018', 'Capital souscrit soumis à des réglementations particulières', 1, TRUE),
  ('102', 'Fonds fiduciaires', 1, TRUE),
  ('104', 'Primes liées au capital', 1, FALSE),
  ('1041', 'Primes d''émission', 1, TRUE),
  ('1042', 'Primes de fusion', 1, TRUE),
  ('1043', 'Primes d''apport', 1, TRUE),
  ('1044', 'Primes de conversion d''obligations en actions', 1, TRUE),
  ('1045', 'Bons de souscription de titres en capital', 1, TRUE),
  ('105', 'Écarts de réévaluation', 1, FALSE),
  ('106', 'Réserves', 1, FALSE),
  ('1061', 'Réserve légale', 1, FALSE),
  ('1062', 'Réserves indisponibles', 1, FALSE),
  ('1063', 'Réserves statutaires ou contractuelles', 1, FALSE),
  ('1064', 'Réserves réglementées', 1, FALSE),
  ('1068', 'Autres réserves', 1, FALSE),
  ('107', 'Écart d''équivalence', 1, FALSE),
  ('108', 'Compte de l''exploitant', 1, FALSE),
  ('109', 'Actionnaires : capital souscrit - non appelé', 1, FALSE),
  ('11', 'Report à nouveau', 1, FALSE),
  ('110', 'Report à nouveau - solde créditeur', 1, FALSE),
  ('119', 'Report à nouveau - solde débiteur', 1, FALSE),
  ('12', 'Résultat de l''exercice', 1, FALSE),
  ('120', 'Résultat de l''exercice - bénéfice', 1, FALSE),
  ('1209', 'Acomptes sur dividendes', 1, TRUE),
  ('129', 'Résultat de l''exercice - perte', 1, FALSE),
  ('13', 'Subventions d''investissement', 1, FALSE),
  ('131', 'Subventions d''investissement octroyées', 1, FALSE),
  ('139', 'Subventions d''investissement inscrites au compte de résultat', 1, FALSE),
  ('14', 'Provisions réglementées', 1, FALSE),
  ('143', 'Provisions réglementées pour hausse de prix', 1, FALSE),
  ('145', 'Amortissements dérogatoires', 1, FALSE),
  ('148', 'Autres provisions réglementées', 1, FALSE),
  ('15', 'Provisions', 1, FALSE),
  ('151', 'Provisions pour risques', 1, FALSE),
  ('1511', 'Provisions pour litiges', 1, TRUE),
  ('1512', 'Provisions pour garanties données aux clients', 1, TRUE),
  ('1514', 'Provisions pour amendes et pénalités', 1, TRUE),
  ('1515', 'Provisions pour pertes de change', 1, TRUE),
  ('1516', 'Provisions pour pertes sur contrats', 1, TRUE),
  ('1518', 'Autres provisions pour risques', 1, TRUE),
  ('152', 'Provisions pour charges', 1, FALSE),
  ('1521', 'Provisions pour pensions et obligations similaires', 1, TRUE),
  ('1522', 'Provisions pour restructurations', 1, TRUE),
  ('1523', 'Provisions pour impôts', 1, TRUE),
  ('1524', 'Provisions pour renouvellement des immobilisations - entreprises concessionnaires', 1, TRUE),
  ('1525', 'Provisions pour gros entretien ou grandes révisions', 1, TRUE),
  ('1526', 'Provisions pour remise en état', 1, TRUE),
  ('1527', 'Autres provisions pour charges', 1, TRUE),
  ('16', 'Emprunts et dettes assimilées, fonds non remboursables et avances conditionnées', 1, FALSE),
  ('161', 'Emprunts obligataires convertibles si non-inscrits dans le compte 167', 1, FALSE),
  ('1618', 'Intérêts courus sur emprunts obligataires convertibles', 1, TRUE),
  ('162', 'Obligations représentatives de passifs nets remis en fiducie si non-inscrites dans le compte 167', 1, FALSE),
  ('163', 'Autres emprunts obligataires si non-inscrits dans le compte 167', 1, FALSE),
  ('1638', 'Intérêts courus sur autres emprunts obligataires', 1, TRUE),
  ('164', 'Emprunts auprès des établissements de crédit si non-inscrits dans le compte 167', 1, FALSE),
  ('1648', 'Intérêts courus sur emprunts auprès des établissements de crédit', 1, TRUE),
  ('165', 'Dépôts et cautionnements reçus', 1, FALSE),
  ('1651', 'Dépôts', 1, TRUE),
  ('1655', 'Cautionnements', 1, TRUE),
  ('1658', 'Intérêts courus sur dépôts et cautionnements reçus', 1, TRUE),
  ('166', 'Participation des salariés aux résultats', 1, FALSE),
  ('1661', 'Comptes bloqués', 1, TRUE),
  ('1662', 'Fonds de participation', 1, TRUE),
  ('1668', 'Intérêts courus sur participation des salariés aux résultats', 1, TRUE),
  ('167', 'Fonds non remboursables et avances conditionnées', 1, FALSE),
  ('1671', 'Fonds non remboursables montant principal', 1, TRUE),
  ('16711', 'Titres participatifs montant principal', 1, TRUE),
  ('16712', 'Autres fonds non remboursables montant principal', 1, TRUE),
  ('1673', 'Avances conditionnées montant principal', 1, TRUE),
  ('1674', 'Avances conditionnées intérêts courus', 1, TRUE),
  ('168', 'Autres emprunts et dettes assimilées', 1, FALSE),
  ('1681', 'Autres emprunts', 1, TRUE),
  ('1682', 'Emprunts participatifs', 1, TRUE),
  ('1685', 'Rentes viagères capitalisées', 1, TRUE),
  ('1687', 'Autres dettes', 1, TRUE),
  ('1688', 'Intérêts courus sur autres emprunts et dettes assimilées', 1, TRUE),
  ('169', 'Primes de remboursement des emprunts', 1, FALSE),
  ('17', 'Dettes rattachées à des participations', 1, FALSE),
  ('171', 'Dettes rattachées à des participations - groupe', 1, FALSE),
  ('174', 'Dettes rattachées à des participations - hors groupe', 1, FALSE),
  ('178', 'Dettes rattachées à des sociétés en participation', 1, FALSE),
  ('18', 'Comptes de liaison des établissements et sociétés en participation', 1, FALSE),
  ('181', 'Comptes de liaison des établissements', 1, FALSE),
  ('186', 'Biens et prestations de services échangés entre établissements - charges', 1, FALSE),
  ('187', 'Biens et prestations de services échangés entre établissements - produits', 1, FALSE),
  ('188', 'Comptes de liaison des sociétés en participation', 1, FALSE),
  ('20', 'Immobilisations incorporelles et frais d''établissement', 2, FALSE),
  ('201', 'Frais d''établissement', 2, FALSE),
  ('2011', 'Frais de constitution', 2, TRUE),
  ('2012', 'Frais de premier établissement', 2, TRUE),
  ('20121', 'Frais de prospection', 2, TRUE),
  ('20122', 'Frais de publicité', 2, TRUE),
  ('2013', 'Frais d''augmentation de capital et d''opérations diverses - fusions, scissions, transformations', 2, TRUE),
  ('203', 'Frais de développement', 2, FALSE),
  ('205', 'Concessions et droits similaires, brevets, licences, marques, procédés, solutions informatiques, droits et valeurs similaires', 2, FALSE),
  ('206', 'Droit au bail', 2, FALSE),
  ('207', 'Fonds commercial', 2, FALSE),
  ('208', 'Autres immobilisations incorporelles', 2, FALSE),
  ('2081', 'Mali de fusion sur actifs incorporels', 2, TRUE),
  ('21', 'Immobilisations corporelles', 2, FALSE),
  ('211', 'Terrains', 2, FALSE),
  ('2111', 'Terrains nus', 2, TRUE),
  ('2112', 'Terrains aménagés', 2, TRUE),
  ('2113', 'Sous-sols et sur-sols', 2, TRUE),
  ('2114', 'Terrains de carrières (Tréfonds)', 2, TRUE),
  ('2115', 'Terrains bâtis', 2, TRUE),
  ('212', 'Agencements et aménagements de terrains', 2, FALSE),
  ('213', 'Constructions', 2, FALSE),
  ('2131', 'Bâtiments', 2, TRUE),
  ('2135', 'Installations générales - agencements - aménagements des constructions', 2, TRUE),
  ('2138', 'Ouvrages d''infrastructure', 2, TRUE),
  ('214', 'Constructions sur sol d''autrui', 2, FALSE),
  ('215', 'Installations techniques, matériels et outillages industriels', 2, FALSE),
  ('2151', 'Installations complexes spécialisées', 2, TRUE),
  ('21511', 'Installations complexes spécialisées sur sol propre', 2, TRUE),
  ('21514', 'Installations complexes spécialisées sur sol d''autrui', 2, TRUE),
  ('2153', 'Installations à caractère spécifique', 2, TRUE),
  ('21531', 'Installations à caractère spécifique sur sol propre', 2, TRUE),
  ('21534', 'Installations à caractère spécifique sur sol d''autrui', 2, TRUE),
  ('2154', 'Matériels industriels', 2, TRUE),
  ('2155', 'Outillages industriels', 2, TRUE),
  ('2157', 'Agencements et aménagements des matériels et outillages industriels', 2, TRUE),
  ('218', 'Autres immobilisations corporelles', 2, FALSE),
  ('2181', 'Installations générales, agencements, aménagements divers', 2, TRUE),
  ('2182', 'Matériel de transport', 2, TRUE),
  ('2183', 'Matériel de bureau et matériel informatique', 2, TRUE),
  ('2184', 'Mobilier', 2, TRUE),
  ('2185', 'Cheptel', 2, TRUE),
  ('2186', 'Emballages récupérables', 2, TRUE),
  ('2187', 'Mali de fusion sur actifs corporels', 2, TRUE),
  ('22', 'Immobilisations mises en concession', 2, FALSE),
  ('229', 'Droits du concédant (présentés dans la rubrique autres fonds propres)', 2, FALSE),
  ('23', 'Immobilisations en cours, avances et acomptes', 2, FALSE),
  ('231', 'Immobilisations corporelles en cours', 2, FALSE),
  ('232', 'Immobilisations incorporelles en cours', 2, FALSE),
  ('237', 'Avances et acomptes versés sur commandes d''immobilisations incorporelles', 2, FALSE),
  ('238', 'Avances et acomptes versés sur commandes d''immobilisations corporelles', 2, FALSE),
  ('26', 'Participations et créances rattachées à des participations', 2, FALSE),
  ('261', 'Titres de participation', 2, FALSE),
  ('2611', 'Actions', 2, TRUE),
  ('2618', 'Autres titres', 2, TRUE),
  ('262', 'Titres évalués par équivalence', 2, FALSE),
  ('266', 'Autres formes de participation', 2, FALSE),
  ('2661', 'Droits représentatifs d''actifs nets remis en fiducie', 2, TRUE),
  ('267', 'Créances rattachées à des participations', 2, FALSE),
  ('2671', 'Créances rattachées à des participations - groupe', 2, TRUE),
  ('2674', 'Créances rattachées à des participations - hors groupe', 2, TRUE),
  ('2675', 'Versements représentatifs d''apports non capitalisés - appel de fonds', 2, TRUE),
  ('2676', 'Avances consolidables', 2, TRUE),
  ('2677', 'Autres créances rattachées à des participations', 2, TRUE),
  ('2678', 'Intérêts courus', 2, TRUE),
  ('268', 'Créances rattachées à des sociétés en participation', 2, FALSE),
  ('2681', 'Principal', 2, TRUE),
  ('2688', 'Intérêts courus', 2, TRUE),
  ('269', 'Versements restant à effectuer sur titres de participation non libérés', 2, FALSE),
  ('27', 'Autres immobilisations financières', 2, FALSE),
  ('271', 'Titres immobilisés autres que les titres immobilisés de l''activité de portefeuille (droit de propriété)', 2, FALSE),
  ('2711', 'Actions', 2, TRUE),
  ('2718', 'Autres titres', 2, TRUE),
  ('272', 'Titres immobilisés (droit de créance)', 2, FALSE),
  ('2721', 'Obligations', 2, TRUE),
  ('2722', 'Bons', 2, TRUE),
  ('273', 'Titres immobilisés de l''activité de portefeuille', 2, FALSE),
  ('274', 'Prêts', 2, FALSE),
  ('2741', 'Prêts participatifs', 2, TRUE),
  ('2742', 'Prêts aux associés', 2, TRUE),
  ('2743', 'Prêts au personnel', 2, TRUE),
  ('2748', 'Autres prêts', 2, TRUE),
  ('275', 'Dépôts et cautionnements versés', 2, FALSE),
  ('2751', 'Dépôts', 2, TRUE),
  ('2755', 'Cautionnements', 2, TRUE),
  ('276', 'Autres créances immobilisées', 2, FALSE),
  ('2761', 'Créances diverses', 2, TRUE),
  ('2768', 'Intérêts courus', 2, TRUE),
  ('27682', 'Intérêts courus sur titres immobilisés (droit de créance)', 2, TRUE),
  ('27684', 'Intérêts courus sur prêts', 2, TRUE),
  ('27685', 'Intérêts courus sur dépôts et cautionnements', 2, TRUE),
  ('27688', 'Intérêts courus sur créances diverses', 2, TRUE),
  ('277', 'Actions propres ou parts propres', 2, FALSE),
  ('2771', 'Actions propres ou parts propres', 2, TRUE),
  ('2772', 'Actions propres ou parts propres en voie d''annulation', 2, TRUE),
  ('278', 'Mali de fusion sur actifs financiers', 2, FALSE),
  ('279', 'Versements restant à effectuer sur titres immobilisés non libérés', 2, FALSE),
  ('28', 'Amortissements des immobilisations', 2, FALSE),
  ('280', 'Amortissements des immobilisations incorporelles et des frais d''établissement', 2, FALSE),
  ('2801', 'Frais d''établissement', 2, TRUE),
  ('2803', 'Frais de développement', 2, TRUE),
  ('2805', 'Concessions et droits similaires, brevets, licences, solutions informatiques, droits et valeurs similaires', 2, TRUE),
  ('2806', 'Droit au bail', 2, TRUE),
  ('2807', 'Fonds commercial', 2, TRUE),
  ('2808', 'Autres immobilisations incorporelles', 2, TRUE),
  ('281', 'Amortissements des immobilisations corporelles', 2, FALSE),
  ('2812', 'Agencements, aménagements de terrains', 2, TRUE),
  ('2813', 'Constructions', 2, TRUE),
  ('2814', 'Constructions sur sol d''autrui', 2, TRUE),
  ('2815', 'Installations, matériel et outillage industriels', 2, TRUE),
  ('2818', 'Autres immobilisations corporelles', 2, TRUE),
  ('28187', 'Amortissement du mali de fusion sur actifs corporels', 2, TRUE),
  ('282', 'Amortissements des immobilisations mises en concession', 2, FALSE),
  ('29', 'Dépréciations des immobilisations', 2, FALSE),
  ('290', 'Dépréciations des immobilisations incorporelles', 2, FALSE),
  ('2901', 'Frais d''établissement', 2, TRUE),
  ('2903', 'Frais de développement', 2, TRUE),
  ('2905', 'Marques, procédés, droits et valeurs similaires', 2, TRUE),
  ('2906', 'Droit au bail', 2, TRUE),
  ('2907', 'Fonds commercial', 2, TRUE),
  ('2908', 'Autres immobilisations incorporelles', 2, TRUE),
  ('29081', 'Dépréciation du mali de fusion sur actifs incorporels', 2, TRUE),
  ('291', 'Dépréciations des immobilisations corporelles', 2, FALSE),
  ('2911', 'Terrains', 2, TRUE),
  ('2912', 'Agencements et aménagements de terrains', 2, TRUE),
  ('2913', 'Constructions', 2, TRUE),
  ('2914', 'Constructions sur sol d''autrui', 2, TRUE),
  ('2915', 'Installations techniques, matériels et outillages industriels', 2, TRUE),
  ('2918', 'Autres immobilisations corporelles', 2, TRUE),
  ('29187', 'Dépréciation du mali de fusion sur actifs corporels', 2, TRUE),
  ('292', 'Dépréciations des immobilisations mises en concession', 2, FALSE),
  ('293', 'Dépréciations des immobilisations en cours', 2, FALSE),
  ('2931', 'Immobilisations corporelles en cours', 2, TRUE),
  ('2932', 'Immobilisations incorporelles en cours', 2, TRUE),
  ('296', 'Dépréciations des participations et créances rattachées à des participations', 2, FALSE),
  ('2961', 'Titres de participation', 2, TRUE),
  ('2962', 'Titres évalués par équivalence', 2, TRUE),
  ('2966', 'Autres formes de participation', 2, TRUE),
  ('2967', 'Créances rattachées à des participations', 2, TRUE),
  ('2968', 'Créances rattachées à des sociétés en participation', 2, TRUE),
  ('297', 'Dépréciations des autres immobilisations financières', 2, FALSE),
  ('2971', 'Titres immobilisés autres que les titres immobilisés de l''activité de portefeuille (droit de propriété)', 2, TRUE),
  ('2972', 'Titres immobilisés (droit de créance)', 2, TRUE),
  ('2973', 'Titres immobilisés de l''activité de portefeuille', 2, TRUE),
  ('2974', 'Prêts', 2, TRUE),
  ('2975', 'Dépôts et cautionnements versés', 2, TRUE),
  ('2976', 'Autres créances immobilisées', 2, TRUE),
  ('31', 'Matières premières et fournitures', 3, FALSE),
  ('32', 'Autres approvisionnements', 3, FALSE),
  ('321', 'Matières consommables', 3, FALSE),
  ('322', 'Fournitures consommables', 3, FALSE),
  ('3221', 'Combustibles', 3, TRUE),
  ('3222', 'Produits d''entretien', 3, TRUE),
  ('3223', 'Fournitures d''atelier et d''usine', 3, TRUE),
  ('3224', 'Fournitures de magasin', 3, TRUE),
  ('3225', 'Fournitures de bureau', 3, TRUE),
  ('326', 'Emballages', 3, FALSE),
  ('3261', 'Emballages perdus', 3, TRUE),
  ('3265', 'Emballages récupérables non identifiables', 3, TRUE),
  ('3267', 'Emballages à usage mixte', 3, TRUE),
  ('33', 'En-cours de production de biens', 3, FALSE),
  ('331', 'Produits en cours', 3, FALSE),
  ('335', 'Travaux en cours', 3, FALSE),
  ('34', 'En-cours de production de services', 3, FALSE),
  ('341', 'Études en cours', 3, FALSE),
  ('345', 'Prestations de services en cours', 3, FALSE),
  ('35', 'Stocks de produits', 3, FALSE),
  ('351', 'Produits intermédiaires', 3, FALSE),
  ('355', 'Produits finis', 3, FALSE),
  ('358', 'Produits résiduels ou matières de récupération', 3, FALSE),
  ('3581', 'Déchets', 3, TRUE),
  ('3585', 'Rebuts', 3, TRUE),
  ('3586', 'Matières de récupération', 3, TRUE),
  ('36', 'Stocks provenant d''immobilisations (compte à ouvrir le cas échéant)', 3, TRUE),
  ('37', 'Stocks de marchandises', 3, FALSE),
  ('38', 'Stocks en voie d''acheminement, mis en dépôt ou donnés en consignation', 3, TRUE),
  ('39', 'Dépréciations des stocks et en-cours', 3, FALSE),
  ('391', 'Dépréciations des matières premières et fournitures', 3, FALSE),
  ('392', 'Dépréciations des autres approvisionnements', 3, FALSE),
  ('393', 'Dépréciations des en-cours de production de biens', 3, FALSE),
  ('394', 'Dépréciations des en-cours de production de services', 3, FALSE),
  ('395', 'Dépréciations des stocks de produits', 3, FALSE),
  ('397', 'Dépréciations des stocks de marchandises', 3, FALSE),
  ('40', 'Fournisseurs et comptes rattachés', 4, FALSE),
  ('401', 'Fournisseurs', 4, FALSE),
  ('4011', 'Fournisseurs - Achats de biens et prestations de services', 4, TRUE),
  ('4017', 'Fournisseurs - Retenues de garantie', 4, TRUE),
  ('403', 'Fournisseurs - Effets à payer', 4, FALSE),
  ('404', 'Fournisseurs d''immobilisations', 4, FALSE),
  ('4041', 'Fournisseurs - Achats d''immobilisations', 4, TRUE),
  ('4047', 'Fournisseurs d''immobilisations - Retenues de garantie', 4, TRUE),
  ('405', 'Fournisseurs d''immobilisations - Effets à payer', 4, FALSE),
  ('408', 'Fournisseurs - Factures non parvenues', 4, FALSE),
  ('4081', 'Fournisseurs', 4, TRUE),
  ('4084', 'Fournisseurs d''immobilisations', 4, TRUE),
  ('4088', 'Fournisseurs - Intérêts courus', 4, TRUE),
  ('409', 'Fournisseurs débiteurs', 4, FALSE),
  ('4091', 'Fournisseurs - Avances et acomptes versés sur commandes', 4, TRUE),
  ('4096', 'Fournisseurs - Créances pour emballages et matériel à rendre', 4, TRUE),
  ('4097', 'Fournisseurs - Autres avoirs', 4, TRUE),
  ('40971', 'Fournisseurs d''exploitation', 4, TRUE),
  ('40974', 'Fournisseurs d''immobilisations', 4, TRUE),
  ('4098', 'Rabais, remises, ristournes à obtenir et autres avoirs non encore reçus', 4, TRUE),
  ('41', 'Clients et comptes rattachés', 4, FALSE),
  ('411', 'Clients', 4, FALSE),
  ('4111', 'Clients - Ventes de biens ou de prestations de services', 4, TRUE),
  ('4117', 'Clients - Retenues de garantie', 4, TRUE),
  ('413', 'Clients - Effets à recevoir', 4, FALSE),
  ('416', 'Clients douteux ou litigieux', 4, FALSE),
  ('418', 'Clients - Produits non encore facturés', 4, FALSE),
  ('4181', 'Clients - Factures à établir', 4, TRUE),
  ('4188', 'Clients - Intérêts courus', 4, TRUE),
  ('419', 'Clients créditeurs', 4, FALSE),
  ('4191', 'Clients - Avances et acomptes reçus sur commandes', 4, TRUE),
  ('4196', 'Clients - Dettes sur emballages et matériels consignés', 4, TRUE),
  ('4197', 'Clients - Autres avoirs', 4, TRUE),
  ('4198', 'Rabais, remises, ristournes à accorder et autres avoirs à établir', 4, TRUE),
  ('42', 'Personnel et comptes rattachés', 4, FALSE),
  ('421', 'Personnel - Rémunérations dues', 4, FALSE),
  ('422', 'Comité social et économique', 4, FALSE),
  ('424', 'Participation des salariés aux résultats', 4, FALSE),
  ('4246', 'Réserve spéciale', 4, TRUE),
  ('4248', 'Comptes courants', 4, TRUE),
  ('425', 'Personnel - Avances et acomptes et autres comptes débiteurs', 4, FALSE),
  ('426', 'Personnel - Dépôts', 4, FALSE),
  ('427', 'Personnel - Oppositions', 4, FALSE),
  ('428', 'Personnel - Charges à payer', 4, FALSE),
  ('4282', 'Dettes provisionnées pour congés à payer', 4, TRUE),
  ('4284', 'Dettes provisionnées pour participation des salariés aux résultats', 4, TRUE),
  ('4286', 'Autres charges à payer', 4, TRUE),
  ('43', 'Sécurité sociale et autres organismes sociaux', 4, FALSE),
  ('431', 'Sécurité sociale', 4, FALSE),
  ('437', 'Autres organismes sociaux', 4, FALSE),
  ('438', 'Organismes sociaux - Charges à payer', 4, FALSE),
  ('4382', 'Charges sociales sur congés à payer', 4, TRUE),
  ('4386', 'Autres charges à payer', 4, TRUE),
  ('439', 'Organismes sociaux - Produits à recevoir', 4, FALSE),
  ('44', 'État et autres collectivités publiques', 4, FALSE),
  ('441', 'État - Subventions et aides à recevoir', 4, FALSE),
  ('442', 'Contributions, impôts et taxes recouvrés pour le compte de l''État', 4, FALSE),
  ('4421', 'Prélèvements à la source (Impôt sur le revenu)', 4, TRUE),
  ('4422', 'Prélèvements forfaitaires non libératoires', 4, TRUE),
  ('4423', 'Retenues et prélèvements sur les distributions', 4, TRUE),
  ('444', 'État - Impôts sur les bénéfices', 4, FALSE),
  ('445', 'État - Taxes sur le chiffre d''affaires', 4, FALSE),
  ('4452', 'TVA due intracommunautaire', 4, TRUE),
  ('4455', 'Taxes sur le chiffre d''affaires à décaisser', 4, TRUE),
  ('44551', 'TVA à décaisser', 4, TRUE),
  ('44558', 'Taxes assimilées à la TVA', 4, TRUE),
  ('4456', 'Taxes sur le chiffre d''affaires déductibles', 4, TRUE),
  ('44562', 'TVA sur immobilisations', 4, TRUE),
  ('44563', 'TVA transférée par d''autres entités', 4, TRUE),
  ('44566', 'TVA sur autres biens et services', 4, TRUE),
  ('44567', 'Crédit de TVA à reporter', 4, TRUE),
  ('44568', 'Taxes assimilées à la TVA', 4, TRUE),
  ('4457', 'Taxes sur le chiffre d''affaires collectées', 4, TRUE),
  ('44571', 'TVA collectée', 4, TRUE),
  ('44578', 'Taxes assimilées à la TVA', 4, TRUE),
  ('4458', 'Taxes sur le chiffre d''affaires à régulariser ou en attente', 4, TRUE),
  ('44581', 'Acomptes - Régime simplifié d''imposition', 4, TRUE),
  ('44583', 'Remboursement de taxes sur le chiffre d''affaires demandé', 4, TRUE),
  ('44584', 'TVA récupérée d''avance', 4, TRUE),
  ('44586', 'Taxes sur le chiffre d''affaires sur factures non parvenues', 4, TRUE),
  ('44587', 'Taxes sur le chiffre d''affaires sur factures à établir', 4, TRUE),
  ('446', 'Obligations cautionnées', 4, FALSE),
  ('447', 'Autres impôts, taxes et versements assimilés', 4, FALSE),
  ('448', 'État - Charges à payer et produits à recevoir', 4, FALSE),
  ('4481', 'État - Charges à Payer', 4, TRUE),
  ('44811', 'Charges fiscales sur congés à payer', 4, TRUE),
  ('44812', 'Charges à payer', 4, TRUE),
  ('4482', 'État - Produits à recevoir', 4, TRUE),
  ('449', 'Quotas d''émission à acquérir', 4, FALSE),
  ('45', 'Groupe et associés', 4, FALSE),
  ('451', 'Groupe', 4, FALSE),
  ('455', 'Associés - Comptes courants', 4, FALSE),
  ('4551', 'Principal', 4, TRUE),
  ('4558', 'Intérêts courus', 4, TRUE),
  ('456', 'Associés - Opérations sur le capital', 4, FALSE),
  ('4561', 'Associés - Comptes d''apport en société', 4, TRUE),
  ('45611', 'Apports en nature', 4, TRUE),
  ('45615', 'Apports en numéraire', 4, TRUE),
  ('4562', 'Apporteurs - Capital appelé, non versé', 4, TRUE),
  ('45621', 'Actionnaires - Capital souscrit et appelé, non versé', 4, TRUE),
  ('45625', 'Associés - Capital appelé, non versé', 4, TRUE),
  ('4563', 'Associés - Versements reçus sur augmentation de capital', 4, TRUE),
  ('4564', 'Associés - Versements anticipés', 4, TRUE),
  ('4566', 'Actionnaires défaillants', 4, TRUE),
  ('4567', 'Associés - Capital à rembourser', 4, TRUE),
  ('457', 'Associés - Dividendes à payer', 4, FALSE),
  ('458', 'Associés - Opérations faites en commun et en GIE', 4, FALSE),
  ('4581', 'Opérations courantes', 4, TRUE),
  ('4588', 'Intérêts courus', 4, TRUE),
  ('46', 'Débiteurs divers et créditeurs divers', 4, FALSE),
  ('462', 'Créances sur cessions d''immobilisations', 4, FALSE),
  ('464', 'Dettes sur acquisitions de valeurs mobilières de placement', 4, FALSE),
  ('465', 'Créances sur cessions de valeurs mobilières de placement', 4, FALSE),
  ('467', 'Divers comptes débiteurs et produits à recevoir', 4, FALSE),
  ('468', 'Divers comptes créditeurs et charges à payer', 4, FALSE),
  ('47', 'Comptes transitoires ou d''attente', 4, FALSE),
  ('471', 'Compte d''attente', 4, FALSE),
  ('472', 'Compte d''attente', 4, FALSE),
  ('473', 'Compte d''attente', 4, FALSE),
  ('474', 'Différences d''évaluation – Actif', 4, FALSE),
  ('4741', 'Différences d''évaluation sur instruments financiers à terme - Actif', 4, TRUE),
  ('4742', 'Différences d''évaluation sur jetons détenus - Actif', 4, TRUE),
  ('4746', 'Différences d''évaluation de jetons sur des passifs - Actif', 4, TRUE),
  ('475', 'Différences d''évaluation – Passif', 4, FALSE),
  ('4751', 'Différences d''évaluation sur instruments financiers à terme - Passif', 4, TRUE),
  ('4752', 'Différences d''évaluation sur jetons détenus - Passif', 4, TRUE),
  ('4756', 'Différences d''évaluation de jetons sur des passifs - Passif', 4, TRUE),
  ('476', 'Différence de conversion - Actif', 4, FALSE),
  ('4761', 'Diminution des créances', 4, TRUE),
  ('4762', 'Augmentation des dettes', 4, TRUE),
  ('4768', 'Différences compensées par couverture de change', 4, TRUE),
  ('477', 'Différences de conversion - Passif', 4, FALSE),
  ('4771', 'Augmentation des créances', 4, TRUE),
  ('4772', 'Diminution des dettes', 4, TRUE),
  ('4778', 'Différences compensées par couverture de change', 4, TRUE),
  ('478', 'Autres comptes transitoires', 4, FALSE),
  ('4781', 'Mali de fusion sur actif circulant', 4, TRUE),
  ('48', 'Comptes de régularisation', 4, FALSE),
  ('481', 'Frais d''émission des emprunts', 4, FALSE),
  ('486', 'Charges constatées d''avance', 4, FALSE),
  ('487', 'Produits constatés d''avance', 4, FALSE),
  ('4871', 'Produits constatés d''avance sur jetons émis', 4, TRUE),
  ('488', 'Comptes de répartition périodique des charges et des produits', 4, FALSE),
  ('4886', 'Charges', 4, TRUE),
  ('4887', 'Produits', 4, TRUE),
  ('49', 'Dépréciations des comptes de tiers', 4, FALSE),
  ('491', 'Dépréciations des comptes de clients', 4, FALSE),
  ('495', 'Dépréciations des comptes du groupe et des associés', 4, FALSE),
  ('4951', 'Comptes du groupe', 4, TRUE),
  ('4955', 'Comptes courants des associés', 4, TRUE),
  ('4958', 'Opérations faites en commun et en GIE', 4, TRUE),
  ('496', 'Dépréciations des comptes de débiteurs divers', 4, FALSE),
  ('4962', 'Créances sur cessions d''immobilisations', 4, TRUE),
  ('4965', 'Créances sur cessions de valeurs mobilières de placement', 4, TRUE),
  ('4967', 'Autres comptes débiteurs', 4, TRUE),
  ('50', 'Valeurs mobilières de placement', 5, FALSE),
  ('502', 'Actions propres', 5, FALSE),
  ('5021', 'Actions destinées à être attribuées aux employés et affectées à des plans déterminés', 5, TRUE),
  ('5022', 'Actions disponibles pour être attribuées aux employés ou pour la régularisation des cours de bourse', 5, TRUE),
  ('503', 'Actions', 5, FALSE),
  ('5031', 'Titres cotés', 5, TRUE),
  ('5035', 'Titres non cotés', 5, TRUE),
  ('504', 'Autres titres conférant un droit de propriété', 5, FALSE),
  ('505', 'Obligations et bons émis par la société et rachetés par elle', 5, FALSE),
  ('506', 'Obligations', 5, FALSE),
  ('5061', 'Titres cotés', 5, TRUE),
  ('5065', 'Titres non cotés', 5, TRUE),
  ('507', 'Bons du Trésor et bons de caisse à court terme', 5, FALSE),
  ('508', 'Autres valeurs mobilières de placement et autres créances assimilées', 5, FALSE),
  ('5081', 'Autres valeurs mobilières', 5, TRUE),
  ('5082', 'Bons de souscription', 5, TRUE),
  ('5088', 'Intérêts courus sur obligations, bons et valeurs assimilés', 5, TRUE),
  ('509', 'Versements restant à effectuer sur valeurs mobilières de placement non libérées', 5, FALSE),
  ('51', 'Banques, établissements financiers et assimilés', 5, FALSE),
  ('511', 'Valeurs à l''encaissement', 5, FALSE),
  ('5111', 'Coupons échus à l''encaissement', 5, TRUE),
  ('5112', 'Chèques à encaisser', 5, TRUE),
  ('5113', 'Effets à l''encaissement', 5, TRUE),
  ('5114', 'Effets à l''escompte', 5, TRUE),
  ('512', 'Banques', 5, FALSE),
  ('5121', 'Comptes en euros', 5, TRUE),
  ('5124', 'Comptes en devises', 5, TRUE),
  ('517', 'Autres organismes financiers', 5, FALSE),
  ('518', 'Intérêts courus', 5, FALSE),
  ('5181', 'Intérêts courus à payer', 5, TRUE),
  ('5188', 'Intérêts courus à recevoir', 5, TRUE),
  ('519', 'Concours bancaires courants', 5, FALSE),
  ('5191', 'Crédit de mobilisation de créances commerciales', 5, TRUE),
  ('5193', 'Mobilisation de créances nées à l''étranger', 5, TRUE),
  ('5198', 'Intérêts courus sur concours bancaires courants', 5, TRUE),
  ('52', 'Instruments financiers à terme et jetons détenus', 5, FALSE),
  ('521', 'Instruments financiers à terme', 5, FALSE),
  ('522', 'Jetons détenus', 5, FALSE),
  ('523', 'Jetons auto-détenus', 5, FALSE),
  ('524', 'Jetons empruntés', 5, FALSE),
  ('53', 'Caisse', 5, FALSE),
  ('58', 'Virements internes', 5, FALSE),
  ('59', 'Dépréciations des comptes financiers', 5, FALSE),
  ('590', 'Dépréciations des valeurs mobilières de placement', 5, FALSE),
  ('5903', 'Actions', 5, TRUE),
  ('5904', 'Autres titres conférant un droit de propriété', 5, TRUE),
  ('5906', 'Obligations', 5, TRUE),
  ('5908', 'Autres valeurs mobilières de placement et créances assimilées', 5, TRUE),
  ('60', 'Achats (sauf 603)', 6, FALSE),
  ('601', 'Achats stockés - Matières premières et fournitures', 6, FALSE),
  ('602', 'Achats stockés - Autres approvisionnements', 6, FALSE),
  ('6021', 'Matières consommables', 6, TRUE),
  ('6022', 'Fournitures consommables', 6, TRUE),
  ('60221', 'Combustibles', 6, TRUE),
  ('60222', 'Produits d''entretien', 6, TRUE),
  ('60223', 'Fournitures d''atelier et d''usine', 6, TRUE),
  ('60224', 'Fournitures de magasin', 6, TRUE),
  ('60225', 'Fourniture de bureau', 6, TRUE),
  ('6026', 'Emballages', 6, TRUE),
  ('60261', 'Emballages perdus', 6, TRUE),
  ('60262', 'Malis sur emballage', 6, TRUE),
  ('60265', 'Emballages récupérables non identifiables', 6, TRUE),
  ('60267', 'Emballages à usage mixte', 6, TRUE),
  ('603', 'Variation des stocks d''approvisionnements et de marchandises', 6, FALSE),
  ('6031', 'Variation des stocks de matières premières et fournitures', 6, TRUE),
  ('6032', 'Variation des stocks des autres approvisionnements', 6, TRUE),
  ('6037', 'Variation des stocks de marchandises', 6, TRUE),
  ('604', 'Achats d''études et prestations de services', 6, FALSE),
  ('605', 'Achats de matériel, équipements et travaux', 6, FALSE),
  ('606', 'Achats non stockés de matière et fournitures', 6, FALSE),
  ('6061', 'Fournitures non stockables (eau, énergie, etc.)', 6, TRUE),
  ('6063', 'Fournitures d''entretien et de petit équipement', 6, TRUE),
  ('6064', 'Fournitures administratives', 6, TRUE),
  ('6068', 'Autres matières et fournitures', 6, TRUE),
  ('607', 'Achats de marchandises', 6, FALSE),
  ('608', 'Frais accessoires incorporés aux achats (compte réservé le cas échéant)', 6, TRUE),
  ('609', 'Rabais, remises et ristournes obtenus sur achats', 6, FALSE),
  ('6098', 'Rabais, remises et ristournes non affectés', 6, TRUE),
  ('61', 'Services extérieurs', 6, FALSE),
  ('611', 'Sous-traitance générale', 6, FALSE),
  ('612', 'Redevances de crédit-bail', 6, FALSE),
  ('6122', 'Crédit-bail mobilier', 6, TRUE),
  ('6125', 'Crédit-bail immobilier', 6, TRUE),
  ('613', 'Locations', 6, FALSE),
  ('6132', 'Locations immobilières', 6, TRUE),
  ('6135', 'Locations mobilières', 6, TRUE),
  ('614', 'Charges locatives et de copropriété', 6, FALSE),
  ('615', 'Entretien et réparation', 6, FALSE),
  ('6152', 'Entretien et réparation sur biens immobiliers', 6, TRUE),
  ('6155', 'Entretien et réparation sur biens mobiliers', 6, TRUE),
  ('6156', 'Maintenance', 6, TRUE),
  ('616', 'Primes d''assurances', 6, FALSE),
  ('6161', 'Multirisques', 6, TRUE),
  ('6162', 'Assurance obligatoire dommage construction', 6, TRUE),
  ('6163', 'Assurance - transport', 6, TRUE),
  ('61636', 'sur achats', 6, TRUE),
  ('61637', 'sur ventes', 6, TRUE),
  ('61638', 'sur autres biens', 6, TRUE),
  ('6164', 'Risques d''exploitation', 6, TRUE),
  ('6165', 'Insolvabilité clients', 6, TRUE),
  ('617', 'Études et recherches', 6, FALSE),
  ('618', 'Divers', 6, FALSE),
  ('6181', 'Documentation générale', 6, TRUE),
  ('6183', 'Documentation technique', 6, TRUE),
  ('6185', 'Frais de colloques, séminaires, conférences', 6, TRUE),
  ('619', 'Rabais, remises et ristournes obtenus sur services extérieurs', 6, FALSE),
  ('62', 'Autres services extérieurs', 6, FALSE),
  ('621', 'Personnel extérieur à l''entité', 6, FALSE),
  ('6211', 'Personnel intérimaire', 6, TRUE),
  ('6214', 'Personnel détaché ou prêté à l''entité', 6, TRUE),
  ('622', 'Rémunérations d''intermédiaires et honoraires', 6, FALSE),
  ('6221', 'Commissions et courtages sur achats', 6, TRUE),
  ('6222', 'Commissions et courtages sur ventes', 6, TRUE),
  ('6224', 'Rémunérations des transitaires', 6, TRUE),
  ('6225', 'Rémunérations d''affacturage', 6, TRUE),
  ('6226', 'Honoraires', 6, TRUE),
  ('6227', 'Frais d''actes et de contentieux', 6, TRUE),
  ('6228', 'Divers', 6, TRUE),
  ('623', 'Publicité, publications, relations publiques', 6, FALSE),
  ('6231', 'Annonces et insertions', 6, TRUE),
  ('6232', 'Échantillons', 6, TRUE),
  ('6233', 'Foires et expositions', 6, TRUE),
  ('6234', 'Cadeaux à la clientèle', 6, TRUE),
  ('6235', 'Primes', 6, TRUE),
  ('6236', 'Catalogues et imprimés', 6, TRUE),
  ('6237', 'Publications', 6, TRUE),
  ('6238', 'Divers (pourboires, dons courants)', 6, TRUE),
  ('624', 'Transports de biens et transports collectifs du personnel', 6, FALSE),
  ('6241', 'Transports sur achats', 6, TRUE),
  ('6242', 'Transports sur ventes', 6, TRUE),
  ('6243', 'Transports entre établissements ou chantiers', 6, TRUE),
  ('6244', 'Transports administratifs', 6, TRUE),
  ('6247', 'Transports collectifs du personnel', 6, TRUE),
  ('6248', 'Divers', 6, TRUE),
  ('625', 'Déplacements, missions et réceptions', 6, FALSE),
  ('6251', 'Voyages et déplacements', 6, TRUE),
  ('6255', 'Frais de déménagement', 6, TRUE),
  ('6256', 'Missions', 6, TRUE),
  ('6257', 'Réceptions', 6, TRUE),
  ('626', 'Frais postaux et de télécommunications', 6, FALSE),
  ('627', 'Services bancaires et assimilés', 6, FALSE),
  ('6271', 'Frais sur titres (achat, vente, garde)', 6, TRUE),
  ('6272', 'Commissions et frais sur émission d''emprunts', 6, TRUE),
  ('6275', 'Frais sur effets', 6, TRUE),
  ('6276', 'Location de coffres', 6, TRUE),
  ('6278', 'Autres frais et commissions sur prestations de services', 6, TRUE),
  ('628', 'Divers', 6, FALSE),
  ('6281', 'Concours divers (cotisations)', 6, TRUE),
  ('6284', 'Frais de recrutement de personnel', 6, TRUE),
  ('629', 'Rabais, remises et ristournes obtenus sur autres services extérieurs', 6, FALSE),
  ('63', 'Impôts, taxes et versements assimilés', 6, FALSE),
  ('631', 'Impôts, taxes et versements assimilés sur rémunérations (administrations des impôts)', 6, FALSE),
  ('6311', 'Taxe sur les salaires', 6, TRUE),
  ('6314', 'Cotisation pour défaut d''investissement obligatoire dans la construction', 6, TRUE),
  ('6318', 'Autres', 6, TRUE),
  ('633', 'Impôts, taxes et versements assimilés sur rémunérations (autres organismes)', 6, FALSE),
  ('6331', 'Versement de transport', 6, TRUE),
  ('6332', 'Allocations logement', 6, TRUE),
  ('6333', 'Contribution unique des employeurs à la formation professionnelle', 6, TRUE),
  ('6334', 'Participation des employeurs à l''effort de construction', 6, TRUE),
  ('6335', 'Versements libératoires ouvrant droit à l''exonération de la taxe d''apprentissage', 6, TRUE),
  ('6338', 'Autres', 6, TRUE),
  ('635', 'Autres impôts, taxes et versements assimilés (administrations des impôts)', 6, FALSE),
  ('6351', 'Impôts directs (sauf impôts sur les bénéfices)', 6, TRUE),
  ('63511', 'Contribution économique territoriale', 6, TRUE),
  ('63512', 'Taxes foncières', 6, TRUE),
  ('63513', 'Autres impôts locaux', 6, TRUE),
  ('63514', 'Taxe sur les véhicules des sociétés', 6, TRUE),
  ('6352', 'Taxe sur le chiffre d''affaires non récupérables', 6, TRUE),
  ('6353', 'Impôts indirects', 6, TRUE),
  ('6354', 'Droits d''enregistrement et de timbre', 6, TRUE),
  ('63541', 'Droits de mutation', 6, TRUE),
  ('6358', 'Autres droits', 6, TRUE),
  ('637', 'Autres impôts, taxes et versements assimilés (autres organismes)', 6, FALSE),
  ('6371', 'Contribution sociale de solidarité à la charge des sociétés', 6, TRUE),
  ('6372', 'Taxes perçues par les organismes publics internationaux', 6, TRUE),
  ('6374', 'Impôts et taxes exigibles à l''étranger', 6, TRUE),
  ('6378', 'Taxes diverses', 6, TRUE),
  ('638', 'Rappel d''impôts (autres qu''impôts sur les bénéfices)', 6, FALSE),
  ('64', 'Charges de personnel', 6, FALSE),
  ('641', 'Rémunérations du personnel', 6, FALSE),
  ('6411', 'Salaires, appointements', 6, TRUE),
  ('6412', 'Congés payés', 6, TRUE),
  ('6413', 'Primes et gratifications', 6, TRUE),
  ('6414', 'Indemnités et avantages divers', 6, TRUE),
  ('6415', 'Supplément familial', 6, TRUE),
  ('644', 'Rémunération du travail de l''exploitant', 6, FALSE),
  ('645', 'Cotisations de sécurité sociale et de prévoyance', 6, FALSE),
  ('6451', 'Cotisations à l''Urssaf', 6, TRUE),
  ('6452', 'Cotisations aux mutuelles', 6, TRUE),
  ('6453', 'Cotisations aux caisses de retraites', 6, TRUE),
  ('6454', 'Cotisations à Pôle emploi', 6, TRUE),
  ('6458', 'Cotisations aux autres organismes sociaux', 6, TRUE),
  ('646', 'Cotisations sociales personnelles de l''exploitant', 6, FALSE),
  ('647', 'Autres cotisations sociales', 6, FALSE),
  ('6471', 'Prestations directes', 6, TRUE),
  ('6472', 'Versements au comité social et économique', 6, TRUE),
  ('6474', 'Versements aux autres œuvres sociales', 6, TRUE),
  ('6475', 'Médecine du travail, pharmacie', 6, TRUE),
  ('648', 'Autres charges de personnel', 6, FALSE),
  ('649', 'Remboursements de charges de personnel', 6, FALSE),
  ('65', 'Autres charges de gestion courante', 6, FALSE),
  ('651', 'Redevances pour concessions, brevets, licences, marques, procédés, solutions informatiques, droits et valeurs similaires', 6, FALSE),
  ('6511', 'Redevances pour concessions, brevets, licences, marques, procédés, solutions informatiques', 6, TRUE),
  ('6516', 'Droits d''auteur et de reproduction', 6, TRUE),
  ('6518', 'Autres droits et valeurs similaires', 6, TRUE),
  ('653', 'Rémunérations de l''activité des administrateurs et des gérants', 6, FALSE),
  ('654', 'Pertes sur créances irrécouvrables', 6, FALSE),
  ('6541', 'Créances de l''exercice', 6, TRUE),
  ('6544', 'Créances des exercices antérieurs', 6, TRUE),
  ('655', 'Quote-part de résultat sur opérations faites en commun', 6, FALSE),
  ('6551', 'Quote-part de bénéfice transférée - comptabilité du gérant', 6, TRUE),
  ('6555', 'Quote-part de perte supportée - comptabilité des associés non gérants', 6, TRUE),
  ('656', 'Pertes de change sur créances et dettes commerciales', 6, FALSE),
  ('657', 'Valeurs comptables des immobilisations incorporelles et corporelles cédées', 6, FALSE),
  ('658', 'Pénalités et autres charges', 6, FALSE),
  ('6581', 'Pénalités sur marchés (et dédits payés sur achats et ventes)', 6, TRUE),
  ('6582', 'Pénalités, amendes fiscales et pénales', 6, TRUE),
  ('6583', 'Malis provenant de clauses d''indexation', 6, TRUE),
  ('6584', 'Lots', 6, TRUE),
  ('6588', 'Opérations de constitution ou liquidation des fiducies', 6, TRUE),
  ('66', 'Charges financières', 6, FALSE),
  ('661', 'Charges d''intérêts', 6, FALSE),
  ('6611', 'Intérêts des emprunts et dettes', 6, TRUE),
  ('66116', 'Intérêts des emprunts et dettes assimilées', 6, TRUE),
  ('66117', 'Intérêts des dettes rattachées à des participations', 6, TRUE),
  ('6612', 'Charges de la fiducie, résultat de la période', 6, TRUE),
  ('6615', 'Intérêts des comptes courants et des dépôts créditeurs', 6, TRUE),
  ('6616', 'Intérêts bancaires et sur opérations de financement (escompte…)', 6, TRUE),
  ('6617', 'Intérêts des obligations cautionnées', 6, TRUE),
  ('6618', 'Intérêts des autres dettes', 6, TRUE),
  ('66181', 'Intérêts des dettes commerciales', 6, TRUE),
  ('66188', 'Intérêts des dettes diverses', 6, TRUE),
  ('664', 'Pertes sur créances liées à des participations', 6, FALSE),
  ('665', 'Escomptes accordés', 6, FALSE),
  ('666', 'Pertes de change financières', 6, FALSE),
  ('667', 'Charges sur cession d''éléments financiers', 6, FALSE),
  ('6671', 'Valeurs comptables des immobilisations financières cédées', 6, TRUE),
  ('6672', 'Charges nettes sur cessions de titres immobilisés de l''activité de portefeuille', 6, TRUE),
  ('6673', 'Charges nettes sur cessions de valeurs mobilières de placement', 6, TRUE),
  ('6674', 'Charges nettes sur cessions de jetons', 6, TRUE),
  ('668', 'Autres charges financières', 6, FALSE),
  ('6683', 'Mali provenant du rachat par l''entité d''actions et obligations émises par elle-même', 6, TRUE),
  ('67', 'Charges exceptionnelles', 6, FALSE),
  ('672', 'Charges sur exercices antérieurs (compte à la disposition des entités)', 6, TRUE),
  ('678', 'Autres charges exceptionnelles', 6, FALSE),
  ('68', 'Dotations aux amortissements, aux dépréciations et aux provisions', 6, FALSE),
  ('681', 'Dotations aux amortissements, aux dépréciations et aux provisions (à inscrire dans les charges d''exploitation)', 6, FALSE),
  ('6811', 'Dotations aux amortissements sur immobilisations incorporelles et corporelles', 6, TRUE),
  ('68111', 'Immobilisations incorporelles et frais d''établissement', 6, TRUE),
  ('68112', 'Immobilisations corporelles', 6, TRUE),
  ('6815', 'Dotations aux provisions d''exploitation', 6, TRUE),
  ('6816', 'Dotations pour dépréciations des immobilisations incorporelles et corporelles', 6, TRUE),
  ('68161', 'Immobilisations incorporelles', 6, TRUE),
  ('68162', 'Immobilisations corporelles', 6, TRUE),
  ('6817', 'Dotations pour dépréciations des actifs circulants', 6, TRUE),
  ('68173', 'Stocks et en-cours', 6, TRUE),
  ('68174', 'Créances', 6, TRUE),
  ('686', 'Dotations aux amortissements, aux dépréciations et aux provisions (à inscrire dans les charges financières)', 6, FALSE),
  ('6861', 'Dotations aux amortissements des primes de remboursement des emprunts', 6, TRUE),
  ('6862', 'Dotations aux amortissements des frais d''émission des emprunts', 6, TRUE),
  ('6865', 'Dotations aux provisions financières', 6, TRUE),
  ('6866', 'Dotations pour dépréciation des éléments financiers', 6, TRUE),
  ('68662', 'Immobilisations financières', 6, TRUE),
  ('68665', 'Valeurs mobilières de placement', 6, TRUE),
  ('687', 'Dotations aux amortissements, aux dépréciations et aux provisions (à inscrire dans les charges exceptionnelles)', 6, FALSE),
  ('6871', 'Dotations aux amortissements exceptionnels des immobilisations', 6, TRUE),
  ('6872', 'Dotations aux provisions réglementées (immobilisations)', 6, TRUE),
  ('68725', 'Amortissements dérogatoires', 6, TRUE),
  ('6873', 'Dotations aux provisions réglementées (stocks)', 6, TRUE),
  ('6874', 'Dotations aux autres provisions réglementées', 6, TRUE),
  ('6875', 'Dotations aux provisions exceptionnelles', 6, TRUE),
  ('6876', 'Dotations pour dépréciations exceptionnelles', 6, TRUE),
  ('69', 'Participation des salariés - Impôts sur les bénéfices et assimilés', 6, FALSE),
  ('691', 'Participation des salariés aux résultats', 6, FALSE),
  ('695', 'Impôts sur les bénéfices', 6, FALSE),
  ('6951', 'Impôts dus en France', 6, TRUE),
  ('6952', 'Contribution additionnelle à l''impôt sur les bénéfices', 6, TRUE),
  ('6954', 'Impôts dus à l''étranger', 6, TRUE),
  ('696', 'Suppléments d''impôt sur les sociétés liés aux distributions', 6, FALSE),
  ('698', 'Intégration fiscale', 6, FALSE),
  ('6981', 'Intégration fiscale - Charges', 6, TRUE),
  ('6989', 'Intégration fiscale - Produits', 6, TRUE),
  ('699', 'Produits - Reports en arrière des déficits', 6, FALSE),
  ('70', 'Ventes de produits fabriqués, prestations de services, marchandises', 7, FALSE),
  ('701', 'Ventes de produits finis', 7, FALSE),
  ('702', 'Ventes de produits intermédiaires', 7, FALSE),
  ('703', 'Ventes de produits résiduels', 7, FALSE),
  ('704', 'Travaux', 7, FALSE),
  ('705', 'Études', 7, FALSE),
  ('706', 'Prestations de services', 7, FALSE),
  ('707', 'Ventes de marchandises', 7, FALSE),
  ('708', 'Produits des activités annexes', 7, FALSE),
  ('7081', 'Produits des services exploités dans l''intérêt du personnel', 7, TRUE),
  ('7082', 'Commissions et courtages', 7, TRUE),
  ('7083', 'Locations diverses', 7, TRUE),
  ('7084', 'Mise à disposition de personnel facturée', 7, TRUE),
  ('7085', 'Ports et frais accessoires facturés', 7, TRUE),
  ('7086', 'Bonis sur reprises d''emballages consignés', 7, TRUE),
  ('7087', 'Bonifications obtenues des clients et primes sur ventes', 7, TRUE),
  ('7088', 'Autres produits d''activités annexes (cessions d''approvisionnements)', 7, TRUE),
  ('709', 'Rabais, remises et ristournes accordés', 7, FALSE),
  ('7091', 'Rabais, remises et ristournes accordés sur ventes de produits finis', 7, TRUE),
  ('7092', 'Rabais, remises et ristournes accordés sur ventes de produits intermédiaires', 7, TRUE),
  ('7094', 'Rabais, remises et ristournes accordés sur travaux', 7, TRUE),
  ('7095', 'Rabais, remises et ristournes accordés sur études', 7, TRUE),
  ('7096', 'Rabais, remises et ristournes accordés sur prestations de services', 7, TRUE),
  ('7097', 'Rabais, remises et ristournes accordés sur ventes de marchandises', 7, TRUE),
  ('7098', 'Rabais, remises et ristournes accordés sur produits des activités annexes', 7, TRUE),
  ('71', 'Production stockée (ou déstockage)', 7, FALSE),
  ('713', 'Variation des stocks des en-cours de production et de produits', 7, FALSE),
  ('7133', 'Variation des en-cours de production de biens', 7, TRUE),
  ('71331', 'Produits en cours', 7, TRUE),
  ('71335', 'Travaux en cours', 7, TRUE),
  ('7134', 'Variation des en-cours de production de services', 7, TRUE),
  ('71341', 'Études en cours', 7, TRUE),
  ('71345', 'Prestations de services en cours', 7, TRUE),
  ('7135', 'Variation des stocks de produits', 7, TRUE),
  ('71351', 'Produits intermédiaires', 7, TRUE),
  ('71355', 'Produits finis', 7, TRUE),
  ('71358', 'Produits résiduels', 7, TRUE),
  ('72', 'Production immobilisée', 7, FALSE),
  ('721', 'Immobilisations incorporelles', 7, FALSE),
  ('722', 'Immobilisations corporelles', 7, FALSE),
  ('74', 'Subventions', 7, FALSE),
  ('741', 'Subventions d''exploitation', 7, FALSE),
  ('742', 'Subventions d''équilibre', 7, FALSE),
  ('747', 'Quote-part des subventions d''investissement virée au résultat de l''exercice', 7, FALSE),
  ('75', 'Autres produits de gestion courante', 7, FALSE),
  ('751', 'Redevances pour concessions, brevets, licences, marques, procédés, solutions informatiques, droits et valeurs similaires', 7, FALSE),
  ('7511', 'Redevances pour concessions, brevets, licences, marques, procédés, solutions informatiques', 7, TRUE),
  ('7516', 'Droits d''auteur et de reproduction', 7, TRUE),
  ('7518', 'Autres droits et valeurs similaires', 7, TRUE),
  ('752', 'Revenus des immeubles non affectés à des activités professionnelles', 7, FALSE),
  ('753', 'Rémunérations de l''activité des administrateurs et des gérants', 7, FALSE),
  ('754', 'Ristournes perçues des coopératives provenant des excédents', 7, FALSE),
  ('755', 'Quote-part de résultat sur opérations faites en commun', 7, FALSE),
  ('7551', 'Quote-part de perte transférée - comptabilité du gérant', 7, TRUE),
  ('7555', 'Quote-part de bénéfice attribuée - comptabilité des associés non-gérants', 7, TRUE),
  ('756', 'Gains de change sur créances et dettes commerciales', 7, FALSE),
  ('757', 'Produits des cessions d''immobilisations incorporelles et corporelles', 7, FALSE),
  ('758', 'Indemnités et autres produits', 7, FALSE),
  ('7581', 'Dédits et pénalités perçus sur achats et ventes', 7, TRUE),
  ('7582', 'Libéralités reçues', 7, TRUE),
  ('7583', 'Rentrées sur créances amorties', 7, TRUE),
  ('7584', 'Dégrèvements d''impôts autres qu''impôts sur les bénéfices', 7, TRUE),
  ('7585', 'Bonis provenant de clauses d''indexation', 7, TRUE),
  ('7586', 'Lots', 7, TRUE),
  ('7587', 'Indemnités d''assurance', 7, TRUE),
  ('7588', 'Opérations de constitution ou liquidation des fiducies', 7, TRUE),
  ('76', 'Produits financiers', 7, FALSE),
  ('761', 'Produits de participations', 7, FALSE),
  ('7611', 'Revenus des titres de participation', 7, TRUE),
  ('7612', 'Produits de la fiducie, résultat de la période', 7, TRUE),
  ('7616', 'Revenus sur autres formes de participation', 7, TRUE),
  ('7617', 'Revenus des créances rattachées à des participations', 7, TRUE),
  ('762', 'Produits des autres immobilisations financières', 7, FALSE),
  ('7621', 'Revenus des titres immobilisés', 7, TRUE),
  ('7626', 'Revenus des prêts', 7, TRUE),
  ('7627', 'Revenus des créances immobilisées', 7, TRUE),
  ('763', 'Revenus des autres créances', 7, FALSE),
  ('7631', 'Revenus des créances commerciales', 7, TRUE),
  ('7638', 'Revenus des créances diverses', 7, TRUE),
  ('764', 'Revenus des valeurs mobilières de placement', 7, FALSE),
  ('765', 'Escomptes obtenus', 7, FALSE),
  ('766', 'Gains de change financiers', 7, FALSE),
  ('767', 'Produits sur cession d''éléments financiers', 7, FALSE),
  ('7671', 'Produits des cessions d''immobilisations financières', 7, TRUE),
  ('7672', 'Produits nets sur cessions de titres immobilisés de l''activité de portefeuille', 7, TRUE),
  ('7673', 'Produits nets sur cessions de valeurs mobilières de placement', 7, TRUE),
  ('7674', 'Produits nets sur cessions de jetons', 7, TRUE),
  ('768', 'Autres produits financiers', 7, FALSE),
  ('7683', 'Bonis provenant du rachat par l''entreprise d''actions et d''obligations émises par elle-même', 7, TRUE),
  ('77', 'Produits exceptionnels', 7, FALSE),
  ('772', 'Produits sur exercices antérieurs (compte à la disposition des entités)', 7, TRUE),
  ('778', 'Autres produits exceptionnels', 7, FALSE),
  ('78', 'Reprises sur amortissements, dépréciations et provisions', 7, FALSE),
  ('781', 'Reprises sur amortissements, dépréciations et provisions (à inscrire dans les produits d''exploitation)', 7, FALSE),
  ('7811', 'Reprises sur amortissements des immobilisations incorporelles et corporelles', 7, TRUE),
  ('78111', 'Immobilisations incorporelles', 7, TRUE),
  ('78112', 'Immobilisations corporelles', 7, TRUE),
  ('7815', 'Reprises sur provisions d''exploitation', 7, TRUE),
  ('7816', 'Reprises sur dépréciations des immobilisations incorporelles et corporelles', 7, TRUE),
  ('78161', 'Immobilisations incorporelles', 7, TRUE),
  ('78162', 'Immobilisations corporelles', 7, TRUE),
  ('7817', 'Reprises sur dépréciations des actifs circulants', 7, TRUE),
  ('78173', 'Stocks et en-cours', 7, TRUE),
  ('78174', 'Créances', 7, TRUE),
  ('786', 'Reprises sur dépréciations et provisions (à inscrire dans les produits financiers)', 7, FALSE),
  ('7865', 'Reprises sur provisions financières', 7, TRUE),
  ('7866', 'Reprises sur dépréciations des éléments financiers', 7, TRUE),
  ('78662', 'Immobilisations financières', 7, TRUE),
  ('78665', 'Valeurs mobilières de placement', 7, TRUE),
  ('787', 'Reprises sur dépréciations et provisions (à inscrire dans les produits exceptionnels)', 7, FALSE),
  ('7872', 'Reprises sur provisions réglementées (immobilisations)', 7, TRUE),
  ('78725', 'Amortissements dérogatoires', 7, TRUE),
  ('7873', 'Reprises sur provisions réglementées (stocks)', 7, TRUE),
  ('7874', 'Reprises sur autres provisions réglementées', 7, TRUE),
  ('7875', 'Reprises sur provisions exceptionnelles', 7, TRUE),
  ('7876', 'Reprises sur dépréciations exceptionnelles', 7, TRUE);
