-- Plan comptable simplifié (147 comptes) + toggle par entreprise.
-- Le plan simplifié contient en plus : categorie (regroupement visuel),
-- mots_cles (aide à la recherche), exemples (doc utilisateur), sens (D/C, utilisé
-- pour filtrer l'autocomplete selon le type débit/crédit de la ligne en cours
-- de saisie) et pcg_parent (lien indicatif vers le compte PCG général).
--
-- L'entreprise peut basculer entre le plan général et le simplifié via la
-- colonne plan_comptable ('general' | 'simplifie'). Le simplifié est le défaut.

CREATE TABLE plan_comptable_simplifie (
    numero VARCHAR(10) PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL,
    categorie VARCHAR(100) NOT NULL,
    mots_cles TEXT,
    exemples TEXT,
    sens CHAR(1) NOT NULL CHECK (sens IN ('D', 'C')),
    pcg_parent VARCHAR(10),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_plan_simplifie_categorie ON plan_comptable_simplifie(categorie);
CREATE INDEX idx_plan_simplifie_sens ON plan_comptable_simplifie(sens);

ALTER TABLE entreprises
    ADD COLUMN plan_comptable VARCHAR(20) NOT NULL DEFAULT 'simplifie'
        CHECK (plan_comptable IN ('general', 'simplifie'));

INSERT INTO plan_comptable_simplifie (numero, libelle, categorie, mots_cles, exemples, sens, pcg_parent) VALUES
  ('101300', 'Capital souscrit, appelé et versé', 'Capitaux propres', 'capital|apport initial|création société', 'Apport à la création de la SASU (ex. 1€ ou 1000€)', 'C', '1013'),
  ('106100', 'Réserve légale', 'Capitaux propres', 'réserve légale|affectation résultat', 'Affectation annuelle de 5% du bénéfice jusqu''à 10% du capital', 'C', '1061'),
  ('106800', 'Autres réserves', 'Capitaux propres', 'réserves|report bénéfice', 'Mise en réserve du résultat après AG', 'C', '1068'),
  ('110000', 'Report à nouveau (solde créditeur)', 'Capitaux propres', 'report à nouveau|RAN|bénéfices antérieurs', 'Bénéfices non distribués des exercices antérieurs', 'C', '110'),
  ('119000', 'Report à nouveau (solde débiteur)', 'Capitaux propres', 'report à nouveau déficit|pertes antérieures', 'Pertes cumulées non encore apurées', 'D', '119'),
  ('120000', 'Résultat de l''exercice — bénéfice', 'Capitaux propres', 'résultat bénéfice|résultat exercice', 'Bénéfice de l''exercice (virement depuis comptes 6/7 à la clôture)', 'C', '120'),
  ('129000', 'Résultat de l''exercice — perte', 'Capitaux propres', 'résultat perte|déficit exercice', 'Perte de l''exercice', 'D', '129'),
  ('164100', 'Emprunt bancaire — capital restant dû', 'Dettes financières', 'emprunt|prêt bancaire|crédit professionnel', 'Prêt pro banque, PGE, prêt BPI', 'C', '164'),
  ('165500', 'Cautionnements reçus', 'Dettes financières', 'caution|dépôt de garantie reçu', 'Dépôt de garantie versé par un locataire', 'C', '1655'),
  ('168700', 'Compte courant d''associé', 'Dettes financières', 'compte courant associé|CCA|apport associé', 'Fonds prêtés par l''associé à la société (remboursables)', 'C', '1687'),
  ('205000', 'Logiciels et licences (> 500€)', 'Immobilisations incorporelles', 'logiciel|licence perpétuelle|logiciel acquis|solution informatique', 'Licence Windows OEM serveur, Adobe achat définitif, logiciel métier onéreux', 'D', '205'),
  ('205100', 'Nom de domaine (immobilisé)', 'Immobilisations incorporelles', 'nom de domaine|domain|immobilisation', 'Achat nom de domaine rare/cher (à activer selon règles)', 'D', '205'),
  ('207000', 'Fonds commercial', 'Immobilisations incorporelles', 'fonds de commerce|fonds commercial|goodwill', 'Rachat d''un fonds de commerce', 'D', '207'),
  ('213100', 'Bâtiments', 'Immobilisations corporelles', 'bâtiment|immeuble|construction', 'Achat local professionnel', 'D', '2131'),
  ('215400', 'Matériel industriel', 'Immobilisations corporelles', 'matériel industriel|machine|outil production', 'Machine de production, équipement atelier', 'D', '2154'),
  ('218200', 'Matériel de transport', 'Immobilisations corporelles', 'voiture|véhicule|camionnette|utilitaire société', 'Achat véhicule professionnel', 'D', '2182'),
  ('218300', 'Matériel de bureau et informatique', 'Immobilisations corporelles', 'ordinateur|PC|mac|serveur|imprimante|écran|GPU|carte graphique|station travail', 'PC portable pro, serveur GPU (RTX 5080), iMac, station de travail, carte graphique professionnelle > 500€', 'D', '2183'),
  ('218400', 'Mobilier de bureau', 'Immobilisations corporelles', 'mobilier|bureau|chaise|meuble|armoire', 'Bureau, fauteuil ergonomique, armoire', 'D', '2184'),
  ('218500', 'Cheptel / autres immobilisations corporelles', 'Immobilisations corporelles', 'autres immobilisations corporelles', 'Autres immobilisations corporelles non classées', 'D', '2188'),
  ('280500', 'Amortissement des immos incorporelles', 'Amortissements', 'amortissement logiciel|dotation amortissement incorporel', 'Amortissement annuel d''un logiciel immobilisé', 'C', '2805'),
  ('281820', 'Amortissement matériel de transport', 'Amortissements', 'amortissement véhicule|dotation voiture', 'Amortissement voiture sur 5 ans', 'C', '28182'),
  ('281830', 'Amortissement matériel informatique', 'Amortissements', 'amortissement ordinateur|dotation matériel informatique', 'Amortissement PC/serveur sur 3 ans', 'C', '28183'),
  ('401000', 'Fournisseurs', 'Tiers — fournisseurs', 'fournisseur|dette fournisseur|facture à payer', 'Dette envers fournisseur sur facture reçue non encore payée', 'C', '401'),
  ('404000', 'Fournisseurs d''immobilisations', 'Tiers — fournisseurs', 'fournisseur immobilisation|dette sur achat matériel', 'Dette envers fournisseur ayant livré une immobilisation', 'C', '404'),
  ('408100', 'Factures non parvenues', 'Tiers — régularisation', 'FNP|factures non parvenues|charge à payer clôture', 'Charge de l''exercice dont la facture n''est pas encore reçue (ex: télécoms décembre)', 'C', '4081'),
  ('409100', 'Acomptes versés aux fournisseurs', 'Tiers — fournisseurs', 'acompte fournisseur|avance fournisseur', 'Acompte versé à un prestataire avant exécution', 'D', '4091'),
  ('411000', 'Clients', 'Tiers — clients', 'client|créance client|facture émise', 'Créance sur facture émise non encore encaissée', 'D', '411'),
  ('411100', 'Clients — ventes prestations de services', 'Tiers — clients', 'client prestation|facture client prestation', 'Créance sur facture de prestation (freelance développement, conseil)', 'D', '4111'),
  ('418100', 'Factures à établir', 'Tiers — régularisation', 'FAE|factures à établir|produit à recevoir', 'Prestation réalisée mais non encore facturée à la clôture', 'D', '4181'),
  ('419100', 'Acomptes reçus de clients', 'Tiers — clients', 'acompte client|avance client', 'Acompte encaissé avant prestation', 'C', '4191'),
  ('421000', 'Personnel — rémunérations dues', 'Personnel', 'salaire dû|net à payer|paie', 'Salaire net à verser après paie', 'C', '421'),
  ('425000', 'Avances et acomptes au personnel', 'Personnel', 'avance salarié|acompte salaire', 'Acompte versé à un salarié avant paie', 'D', '425'),
  ('431000', 'URSSAF / Sécurité sociale — à payer', 'Social', 'URSSAF|sécurité sociale|cotisations à payer|SSI|charges sociales', 'Cotisations sociales collectées et à reverser (URSSAF, SSI)', 'C', '431'),
  ('437000', 'Autres organismes sociaux', 'Social', 'retraite|prévoyance|mutuelle|APICIL|AG2R|Humanis', 'Caisse retraite complémentaire, prévoyance, mutuelle obligatoire', 'C', '437'),
  ('442100', 'Prélèvement à la source (PAS)', 'Fiscal', 'PAS|prélèvement à la source|impôt sur le revenu salarié', 'IR retenu sur salaire à reverser à la DGFiP', 'C', '4421'),
  ('444000', 'Impôt sur les sociétés', 'Fiscal', 'IS|impôt sociétés|acompte IS|solde IS', 'Acomptes et solde d''IS à payer à la DGFiP', 'C', '444'),
  ('445200', 'TVA due intracommunautaire (autoliquidation)', 'TVA', 'TVA autoliquidée|TVA intracom|TVA OpenAI|TVA Anthropic|TVA services étrangers|autoliquidation', 'TVA collectée sur services UE/hors UE reçus (OpenAI, Anthropic, AWS Irlande, Cloudflare)', 'C', '4452'),
  ('445510', 'TVA à décaisser', 'TVA', 'TVA à payer|solde TVA|TVA à décaisser', 'Solde TVA à payer lors de la déclaration CA3', 'C', '44551'),
  ('445620', 'TVA déductible sur immobilisations', 'TVA', 'TVA immobilisation|TVA matériel informatique|TVA déductible immo', 'TVA sur achat de PC, serveur, voiture immobilisée', 'D', '44562'),
  ('445660', 'TVA déductible sur biens et services', 'TVA', 'TVA déductible|TVA sur achats|TVA courante', 'TVA sur la plupart des achats courants (fournitures, SaaS, honoraires)', 'D', '44566'),
  ('445670', 'Crédit de TVA à reporter', 'TVA', 'crédit TVA|TVA à reporter|remboursement TVA', 'TVA déductible > TVA collectée sur la déclaration', 'D', '44567'),
  ('445710', 'TVA collectée', 'TVA', 'TVA collectée|TVA sur ventes|TVA facturée', 'TVA facturée aux clients', 'C', '44571'),
  ('455000', 'Associé — compte courant', 'Associés', 'compte courant associé|CCA|apport associé|avance associé', 'Fonds prêtés/retirés par l''associé (SASU, EURL)', 'C', '4551'),
  ('457000', 'Associés — dividendes à payer', 'Associés', 'dividende|distribution|dividende à verser', 'Dividendes votés en AG mais non encore versés', 'C', '457'),
  ('467000', 'Autres comptes débiteurs ou créditeurs', 'Tiers — divers', 'divers débiteur créditeur|autres tiers', 'Tiers divers non classés ailleurs', 'C', '467'),
  ('486000', 'Charges constatées d''avance (CCA)', 'Régularisation', 'CCA|charge constatée d''avance|abonnement annuel à cheval|cut-off charge', 'Partie d''un abonnement annuel (nom de domaine, assurance, SaaS annuel) couvrant l''exercice suivant', 'D', '486'),
  ('487000', 'Produits constatés d''avance (PCA)', 'Régularisation', 'PCA|produit constaté d''avance|acompte facturé', 'Prestation facturée d''avance couvrant l''exercice suivant', 'C', '487'),
  ('512100', 'Banque — compte en euros (principal)', 'Trésorerie', 'banque|compte bancaire|compte pro|Shine|Qonto|Revolut|Crédit Agricole', 'Compte courant pro principal (mouvements quotidiens)', 'D', '5121'),
  ('512110', 'Banque — compte secondaire', 'Trésorerie', 'banque secondaire|deuxième compte|livret pro', 'Deuxième compte bancaire pro ou livret d''épargne pro', 'D', '5121'),
  ('512400', 'Banque — compte en devises', 'Trésorerie', 'compte devises|compte USD|compte dollar|wise|multi-devises', 'Compte USD/GBP (ex. Wise, Revolut Business multi-devises)', 'D', '5124'),
  ('517000', 'Autres organismes financiers (Paypal, Stripe, Wise)', 'Trésorerie', 'paypal|stripe|wise|revolut|neo-banque|solde plateforme', 'Solde Paypal, Stripe, Wise avant virement vers banque', 'D', '517'),
  ('530000', 'Caisse', 'Trésorerie', 'caisse|espèces|cash', 'Espèces en caisse', 'D', '530'),
  ('580000', 'Virements internes', 'Trésorerie', 'virement interne|transfert banque à banque|virement compte à compte', 'Virement entre deux comptes de la société (compte de passage)', 'D', '580'),
  ('606300', 'Fournitures d''entretien et petit équipement', 'Achats — petit équipement', 'petit matériel|câble|clavier|souris|USB|adaptateur|petit équipement|matériel < 500€|non stocké', 'Câble HDMI, souris, clavier, webcam, disque SSD externe, petit matériel informatique < 500€ HT', 'D', '6063'),
  ('606400', 'Fournitures administratives', 'Achats — petit équipement', 'fournitures bureau|papeterie|cartouche encre|ramette papier|stylo', 'Papier, stylos, cartouches d''encre, classeurs, toner imprimante', 'D', '6064'),
  ('606800', 'Autres matières et fournitures', 'Achats', 'fournitures diverses|consommables', 'Consommables divers liés à l''activité', 'D', '6068'),
  ('607000', 'Achats de marchandises', 'Achats', 'marchandises|stock revente|achat pour revente', 'Achats de biens destinés à être revendus', 'D', '607'),
  ('611000', 'Sous-traitance', 'Services extérieurs', 'sous-traitance|sous-traitant|freelance sous-traité|prestataire délégué', 'Mission déléguée à un autre freelance, développement sous-traité', 'D', '611'),
  ('612200', 'Crédit-bail mobilier', 'Services extérieurs', 'leasing|crédit-bail|LOA mobilier', 'Leasing matériel informatique, crédit-bail véhicule', 'D', '6122'),
  ('613200', 'Locations immobilières', 'Services extérieurs', 'loyer bureau|location local|coworking longue durée', 'Loyer bureau, local professionnel, coworking fixe', 'D', '6132'),
  ('613500', 'Locations mobilières / SaaS', 'Services extérieurs', 'SaaS|abonnement logiciel|Claude|ChatGPT|Notion|Slack|GitHub|Figma|Adobe|Microsoft 365|Google Workspace|Zoom', 'Abonnements SaaS (Claude, ChatGPT, Microsoft 365, Adobe, Notion, Slack, GitHub, Figma, Zoom...). Recommandation PCG récente pour la location de logiciels.', 'D', '6135'),
  ('613510', 'Hébergement web / Cloud (IaaS, PaaS)', 'Services extérieurs', 'hébergement|OVH|AWS|GCP|Azure|Hetzner|DigitalOcean|cloud|VPS|Cloudflare|nom de domaine renouvellement', 'Hébergement web OVH, serveur VPS Hetzner, AWS, Cloudflare, renouvellement nom de domaine', 'D', '6135'),
  ('614000', 'Charges de copropriété', 'Services extérieurs', 'charges copropriété|charges locatives|syndic', 'Charges de copropriété sur local loué ou détenu', 'D', '614'),
  ('615200', 'Entretien et réparation (immobilier)', 'Services extérieurs', 'entretien local|réparation bureau|peinture|plomberie', 'Travaux d''entretien sur le local pro', 'D', '6152'),
  ('615500', 'Entretien et réparation (matériel)', 'Services extérieurs', 'réparation ordinateur|entretien matériel|réparation véhicule|garage', 'Réparation PC, révision véhicule pro', 'D', '6155'),
  ('615600', 'Maintenance', 'Services extérieurs', 'maintenance informatique|contrat maintenance|support technique', 'Contrat de maintenance logicielle/matérielle', 'D', '6156'),
  ('616100', 'Assurance multirisque', 'Services extérieurs', 'assurance multirisque|assurance locaux|assurance bureau', 'Multirisque professionnelle (local, matériel)', 'D', '6161'),
  ('616300', 'Assurance transport', 'Services extérieurs', 'assurance véhicule|assurance auto pro', 'Assurance véhicule de société', 'D', '6163'),
  ('616400', 'Assurance responsabilité civile pro (RC Pro)', 'Services extérieurs', 'RC Pro|responsabilité civile|assurance professionnelle|risques exploitation', 'RC Pro freelance, assurance risques exploitation', 'D', '6164'),
  ('617000', 'Études et recherches', 'Services extérieurs', 'études de marché|R&D externalisée|recherche externe', 'Études externes, veille technologique payante', 'D', '617'),
  ('618100', 'Documentation générale', 'Services extérieurs', 'livre professionnel|abonnement presse|documentation', 'Livres pro, abonnements magazines', 'D', '6181'),
  ('618300', 'Documentation technique', 'Services extérieurs', 'documentation technique|livre technique|cours en ligne|Udemy|Coursera|formation vidéo|OReilly', 'Livres techniques, cours en ligne Udemy/Coursera, abonnement O''Reilly', 'D', '6183'),
  ('618500', 'Colloques, séminaires, conférences', 'Services extérieurs', 'conférence|séminaire|salon professionnel|meetup|devoxx|billet conférence', 'Billets conférence tech, salon pro, inscription meetup payant', 'D', '6185'),
  ('621100', 'Personnel intérimaire', 'Autres services ext.', 'intérim|intérimaire|agence travail temporaire', 'Facture d''agence d''intérim', 'D', '6211'),
  ('622200', 'Commissions sur ventes', 'Autres services ext.', 'commission apporteur|commission ventes|courtage ventes|Malt frais|ComeUp frais|Fiverr frais', 'Commission plateforme Malt, ComeUp, Fiverr sur prestations vendues', 'D', '6222'),
  ('622600', 'Honoraires', 'Autres services ext.', 'honoraires|expert-comptable|avocat|notaire|consultant|conseil|honoraire prestation', 'Expert-comptable, avocat, notaire, consultant, traducteur (prestations intellectuelles)', 'D', '6226'),
  ('622700', 'Frais d''actes et de contentieux', 'Autres services ext.', 'frais actes|huissier|contentieux|procédure', 'Huissier, frais de procédure, dépôt marque INPI', 'D', '6227'),
  ('623100', 'Annonces et insertions', 'Autres services ext.', 'Google Ads|Facebook Ads|LinkedIn Ads|publicité|SEA|annonce', 'Campagnes Google/Meta/LinkedIn Ads, annonces presse', 'D', '6231'),
  ('623400', 'Cadeaux à la clientèle', 'Autres services ext.', 'cadeau client|fin d''année|carte cadeau client', 'Cadeaux clients (plafond fiscal 73€ TTC/bénéficiaire en 2025)', 'D', '6234'),
  ('623600', 'Catalogues et imprimés', 'Autres services ext.', 'plaquette|brochure|flyer|carte de visite|impression', 'Plaquettes commerciales, cartes de visite, flyers', 'D', '6236'),
  ('623700', 'Publications', 'Autres services ext.', 'publication|article sponsorisé|communiqué presse', 'Article sponsorisé, communiqué de presse diffusé', 'D', '6237'),
  ('624100', 'Transports sur achats', 'Autres services ext.', 'frais de port achat|livraison achat|transport achat', 'Frais de port sur achats (Colissimo, Chronopost sur fournitures)', 'D', '6241'),
  ('624200', 'Transports sur ventes', 'Autres services ext.', 'frais de port vente|expédition client|livraison client', 'Frais d''expédition aux clients (e-commerce)', 'D', '6242'),
  ('625100', 'Voyages et déplacements', 'Autres services ext.', 'train|SNCF|avion|taxi|Uber|billet transport|déplacement', 'Train SNCF, avion, taxi/Uber pro, péages, parking', 'D', '6251'),
  ('625600', 'Missions (hébergement et repas en déplacement)', 'Autres services ext.', 'hôtel|Airbnb pro|repas déplacement|per diem|nuitée', 'Hôtel, Airbnb pro, repas lors d''un déplacement (TVA non déductible sur repas)', 'D', '6256'),
  ('625700', 'Réceptions, restaurants clients', 'Autres services ext.', 'restaurant client|invitation|réception|déjeuner affaires', 'Restaurant avec client/prospect (TVA non déductible)', 'D', '6257'),
  ('626000', 'Frais postaux et télécommunications', 'Autres services ext.', 'internet|téléphone|mobile|fibre|forfait mobile|La Poste|timbres|SMS', 'Forfait mobile pro, fibre, timbres, Colissimo, SMS pro', 'D', '626'),
  ('627000', 'Services bancaires', 'Autres services ext.', 'frais bancaires|commission banque|agios|cotisation carte bancaire|frais virement|frais SEPA', 'Frais de tenue de compte, cotisation CB pro, frais de virement SEPA/international', 'D', '627'),
  ('628100', 'Cotisations syndicales / professionnelles', 'Autres services ext.', 'syndicat|cotisation professionnelle|adhésion syndicat|ordre professionnel', 'Cotisation syndicat patronal, ordre professionnel', 'D', '6281'),
  ('628400', 'Frais de recrutement', 'Autres services ext.', 'recrutement|annonce emploi|cabinet recrutement|LinkedIn recruteur', 'Annonces emploi, cabinet de recrutement, abonnement LinkedIn Recruiter', 'D', '6284'),
  ('628800', 'Autres services extérieurs (SaaS — option alternative)', 'Autres services ext.', 'divers services|SaaS alternatif|ChatGPT option|services divers', 'Compte fourre-tout pour services divers non classés (parfois utilisé pour SaaS en alternative au 6135)', 'D', '6288'),
  ('631100', 'Taxe sur les salaires', 'Impôts et taxes', 'taxe sur salaires', 'Taxe sur les salaires (si pas assujetti TVA)', 'D', '6311'),
  ('633300', 'Contribution formation professionnelle', 'Impôts et taxes', 'formation professionnelle|CFP|contribution formation', 'Contribution unique employeurs à la formation professionnelle', 'D', '6333'),
  ('635100', 'Impôts directs (hors IS)', 'Impôts et taxes', 'CFE|cotisation foncière entreprises|taxe foncière|CVAE', 'CFE (cotisation foncière des entreprises), CVAE, taxe foncière locaux', 'D', '6351'),
  ('635400', 'Droits d''enregistrement et de timbre', 'Impôts et taxes', 'droits enregistrement|timbre fiscal|greffe', 'Frais de greffe, droits d''enregistrement statuts, timbres fiscaux', 'D', '6354'),
  ('637800', 'CSG déductible / taxes diverses', 'Impôts et taxes', 'CSG déductible|taxe diverse|contribution divers', 'Part CSG déductible (TNS), autres taxes non classées', 'D', '6378'),
  ('641100', 'Salaires et appointements', 'Personnel', 'salaire brut|appointement|rémunération personnel|paie|salaire président SASU|salaire gérant', 'Salaire brut des salariés et du président SASU (assimilé salarié)', 'D', '6411'),
  ('641200', 'Congés payés', 'Personnel', 'congés payés|CP|provision congés', 'Indemnités de congés payés', 'D', '6412'),
  ('641300', 'Primes et gratifications', 'Personnel', 'prime|bonus|gratification|13e mois', 'Primes annuelles, bonus, 13e mois', 'D', '6413'),
  ('644000', 'Rémunération de l''exploitant (EI)', 'Personnel', 'rémunération exploitant|EI|entreprise individuelle', 'Rémunération de l''entrepreneur individuel (EI uniquement — pas SASU)', 'D', '644'),
  ('645100', 'Cotisations URSSAF (employeur)', 'Personnel', 'URSSAF|charges patronales|sécurité sociale employeur|cotisations patronales', 'Charges patronales URSSAF sur salaire président SASU ou salariés', 'D', '6451'),
  ('645200', 'Cotisations mutuelle', 'Personnel', 'mutuelle|complémentaire santé', 'Part employeur mutuelle obligatoire', 'D', '6452'),
  ('645300', 'Cotisations caisses de retraite', 'Personnel', 'retraite|AGIRC|ARRCO|retraite complémentaire|Humanis|AG2R', 'Retraite complémentaire (AGIRC-ARRCO)', 'D', '6453'),
  ('645400', 'Cotisations Pôle Emploi / France Travail', 'Personnel', 'Pôle Emploi|France Travail|chômage|assurance chômage', 'Cotisations assurance chômage', 'D', '6454'),
  ('645800', 'Autres cotisations sociales', 'Personnel', 'prévoyance|APEC|autres cotisations', 'Prévoyance, APEC, autres cotisations non classées', 'D', '6458'),
  ('646000', 'Cotisations sociales de l''exploitant (TNS)', 'Personnel', 'cotisations TNS|SSI|gérant majoritaire|EURL|EI cotisations personnelles', 'Cotisations sociales personnelles TNS (gérant majoritaire EURL, EI). PAS pour SASU.', 'D', '646'),
  ('647500', 'Médecine du travail', 'Personnel', 'médecine travail|visite médicale|SMIT', 'Cotisation médecine du travail', 'D', '6475'),
  ('651100', 'Redevances logiciels / licences / brevets', 'Charges de gestion', 'redevance|licence|brevet|marque|droits usage', 'Redevances marques/brevets, licences logicielles (option alternative au 6135)', 'D', '6511'),
  ('651600', 'Droits d''auteur', 'Charges de gestion', 'droits d''auteur|licence image|Shutterstock|Getty|stock photo', 'Droits d''auteur, banques d''images (Shutterstock, Adobe Stock, Getty)', 'D', '6516'),
  ('653000', 'Jetons de présence / rémunération administrateurs', 'Charges de gestion', 'jeton présence|administrateur|conseil administration', 'Rémunération des administrateurs (SA)', 'D', '653'),
  ('654000', 'Pertes sur créances irrécouvrables', 'Charges de gestion', 'créance irrécouvrable|impayé client|client insolvable', 'Client définitivement insolvable (après procédure)', 'D', '654'),
  ('656000', 'Pertes de change sur créances/dettes commerciales', 'Charges de gestion', 'perte de change|écart change négatif commercial', 'Perte de change sur facture en USD/GBP (exploitation)', 'D', '656'),
  ('661100', 'Intérêts des emprunts', 'Charges financières', 'intérêts emprunt|intérêts prêt|agios emprunt', 'Intérêts sur prêt bancaire, PGE', 'D', '6611'),
  ('661500', 'Intérêts comptes courants associés', 'Charges financières', 'intérêts CCA|intérêts compte courant associé', 'Intérêts versés aux associés sur leur CCA', 'D', '6615'),
  ('666000', 'Pertes de change financières', 'Charges financières', 'perte change financière|écart change financier', 'Perte de change sur opérations financières (prêts, emprunts devises)', 'D', '666'),
  ('668000', 'Autres charges financières', 'Charges financières', 'frais financiers divers|escompte accordé', 'Escomptes accordés, charges financières diverses', 'D', '668'),
  ('671200', 'Pénalités et amendes fiscales / pénales', 'Charges exceptionnelles', 'amende|pénalité|majoration retard|intérêts retard fiscal', 'Amendes, pénalités de retard URSSAF/DGFiP, contraventions', 'D', '6712'),
  ('671800', 'Autres charges exceptionnelles sur opérations de gestion', 'Charges exceptionnelles', 'charge exceptionnelle|dons|mécénat|perte exceptionnelle', 'Dons, mécénat, pertes exceptionnelles non classées', 'D', '6718'),
  ('675000', 'Valeur comptable des immobilisations cédées', 'Charges exceptionnelles', 'cession immobilisation|VNC|sortie immobilisation', 'Sortie du bilan d''une immobilisation cédée', 'D', '675'),
  ('681110', 'Dotations amortissements immos incorporelles', 'Dotations', 'dotation amortissement logiciel|amortissement incorporel', 'Dotation annuelle amortissement logiciels/brevets', 'D', '68111'),
  ('681120', 'Dotations amortissements immos corporelles', 'Dotations', 'dotation amortissement matériel|amortissement corporel|amortissement PC|amortissement voiture', 'Dotation annuelle amortissement matériel informatique, véhicules', 'D', '68112'),
  ('681174', 'Dotations dépréciations créances clients', 'Dotations', 'dépréciation client|provision client douteux', 'Provision pour client douteux', 'D', '68174'),
  ('695100', 'Impôt sur les sociétés (France)', 'Impôts sur les bénéfices', 'IS|impôt sociétés|acompte IS|impôt bénéfices', 'IS dû en France', 'D', '6951'),
  ('704000', 'Travaux', 'Ventes', 'travaux|chantier|BTP', 'Facturation de travaux (BTP)', 'C', '704'),
  ('705000', 'Études', 'Ventes', 'étude|audit|conseil étude|diagnostic', 'Facturation d''études, audits, conseils', 'C', '705'),
  ('706000', 'Prestations de services', 'Ventes', 'prestation|freelance|développement|consulting|dev web|IA|LLM|déploiement', 'Facturation de prestations (développement, conseil IT, déploiement LLM, infogérance, formation)', 'C', '706'),
  ('706100', 'Prestations de services — France', 'Ventes', 'prestation France|facturation française|client français', 'Prestations facturées à des clients français (TVA 20%)', 'C', '706'),
  ('706200', 'Prestations de services — UE B2B', 'Ventes', 'prestation UE|client européen|TVA intracom|exonération UE', 'Prestations B2B vers l''UE (exonération TVA, autoliquidation par le client)', 'C', '706'),
  ('706300', 'Prestations de services — hors UE', 'Ventes', 'prestation hors UE|export service|client étranger hors UE|USA|UK|Suisse', 'Prestations vers clients hors UE (hors champ TVA)', 'C', '706'),
  ('707000', 'Ventes de marchandises', 'Ventes', 'vente marchandise|revente|e-commerce|boutique', 'Ventes de biens achetés puis revendus', 'C', '707'),
  ('708300', 'Locations diverses', 'Produits annexes', 'location sous-location|mise à disposition matériel', 'Sous-locations, mise à disposition de matériel', 'C', '7083'),
  ('708400', 'Refacturation de personnel', 'Produits annexes', 'refacturation salaire|mise à disposition personnel', 'Refacturation de mise à disposition de personnel', 'C', '7084'),
  ('708500', 'Ports et frais accessoires refacturés', 'Produits annexes', 'refacturation port|frais livraison refacturés', 'Frais de port refacturés aux clients', 'C', '7085'),
  ('709600', 'Rabais, remises, ristournes accordés — prestations', 'Ventes', 'remise accordée|RRR prestations|réduction facture', 'Remises/ristournes accordées sur prestations', 'D', '7096'),
  ('740000', 'Subventions d''exploitation', 'Subventions', 'subvention exploitation|aide publique|aide France Travail|ARE', 'Subventions reçues (hors investissement)', 'C', '741'),
  ('751100', 'Redevances concédées (licences, brevets)', 'Produits de gestion', 'redevance licence|royalty|droits usage concédés', 'Redevances reçues sur brevets/licences concédés', 'C', '7511'),
  ('751600', 'Droits d''auteur perçus', 'Produits de gestion', 'droits auteur reçus|royalties auteur', 'Droits d''auteur reçus', 'C', '7516'),
  ('756000', 'Gains de change sur créances/dettes commerciales', 'Produits de gestion', 'gain change commercial|écart positif change', 'Gain de change sur facture USD/GBP (exploitation)', 'C', '756'),
  ('758100', 'Dédits et pénalités perçus', 'Produits de gestion', 'pénalité reçue|dédit perçu|indemnité client', 'Pénalités de retard facturées aux clients', 'C', '7581'),
  ('758700', 'Indemnités d''assurance', 'Produits de gestion', 'indemnité assurance|remboursement assurance', 'Indemnités reçues de l''assurance', 'C', '7587'),
  ('761100', 'Revenus de titres de participation', 'Produits financiers', 'dividendes reçus|participation|filiale', 'Dividendes reçus de filiales', 'C', '7611'),
  ('762600', 'Revenus des prêts', 'Produits financiers', 'intérêts prêt|intérêts compte courant associé reçus', 'Intérêts reçus sur prêts accordés', 'C', '7626'),
  ('764000', 'Revenus des valeurs mobilières de placement (VMP)', 'Produits financiers', 'intérêts livret|intérêts placement|OPCVM revenus', 'Intérêts livrets pro, revenus VMP', 'C', '764'),
  ('765000', 'Escomptes obtenus', 'Produits financiers', 'escompte reçu|remise règlement anticipé', 'Escomptes pour règlement anticipé', 'C', '765'),
  ('766000', 'Gains de change financiers', 'Produits financiers', 'gain change financier', 'Gain de change sur opérations financières', 'C', '766'),
  ('778000', 'Autres produits exceptionnels', 'Produits exceptionnels', 'produit exceptionnel|remboursement exceptionnel', 'Produits exceptionnels non classés', 'C', '778'),
  ('791000', 'Transferts de charges d''exploitation', 'Transferts', 'transfert charges|remboursement charge|refacturation charges', 'Remboursements de charges (ex. IJSS, charges refacturées)', 'C', '791');
